### ISSUE TITLE
doubt on BEV generation

### ISSUE THREAD

**Issue by srinivasrama** [zhk779/avp_slam--semantic#1]
@zhk779 how do you perform BEV?

**Comment by zhk779** [comment]
You can get the answer from the repos below：
https://github.com/JokerEyeAdas/AdasSourrondView
https://github.com/neozhaoliang/surround-view-system-introduction
I just added some code to get the images.

**Comment by zhk779** [comment]
In addtion, you should caliberate your cameras use the code in the second repo which i mentioned.

**Comment by srinivasrama** [comment]
thank you for the pointers @zhk779
