### ISSUE TITLE
run the virtual demo

### ISSUE THREAD

**Issue by tangqitao** [zhk779/avp_slam--semantic#2]
hello,I'm doing avp slam.I want to run your demo,but don't have the gazebo simulation environment. could you share your simulation environment？ If possible, I would greatly appreciate it

**Comment by zhk779** [comment]
Sorry, i forgot a lot of details about this repo, but the martirials to build the sim env is in the document
simenv_pkg/worlds/my_calibration_plane , U may figure out how to use it in your project
